=== Rodrigo816/Create-chronicles-bosses-and-beyond/config/valkyrienskies/schemas/vs_eureka_server.schema.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "type" : "object",
  "properties" : {
    "allowDisassembly" : {
      "type" : "boolean",
      "description" : "Whether or not disassembly is permitted"
    },
    "antiVelocityMassRelevance" : {
      "type" : "number",
      "format" : "double",
      "description" : "How much inertia affects Eureka ships. Max 10 = full inertia"
    },
    "ballastNoWeight" : {
      "type" : "number",
      "format" : "double",
      "description" : "Weight of ballast when highest redstone power"
    },
    "ballastWeight" : {
      "type" : "number",
      "format" : "double",
      "description" : "Weight of ballast when lowest redstone power"
    },
    "balloonElevationMaxSpeed" : {
      "type" : "number",
      "format" : "double",
      "description" : "The max elevation speed boost gained by having extra extra balloons"
    },
    "baseImpulseElevationRate" : {
      "type" : "number",
      "format" : "double",
      "description" : "Vertical sensitivity up ascend/descend"
    },
    "baseSpeed" : {
      "type" : "number",
      "format" : "double",
      "description" : "The speed a ship with no engines can move at"
    },
    "blockBlacklist" : {
      "description" : "Blacklist of blocks that don't get assembled",
      "type" : "array",
      "items" : {
        "type" : "string",
        "description" : "Blacklist of blocks that don't get assembled"
      }
    },
    "diagonals" : {
      "type" : "boolean",
      "description" : "Whether the ship helm assembles diagonally connected blocks or not"
    },
    "doFluidDrag" : {
      "type" : "boolean",
      "description" : "Allow Eureka controlled ships to be affected by fluid drag"
    },
    "elevationSnappiness" : {
      "type" : "number",
      "format" : "double",
      "description" : "Ascend and descend acceleration"
    },
    "engineFuelMultiplier" : {
      "type" : "number",
      "format" : "float",
      "description" : "Fuel burn time multiplier"
    },
    "engineFuelSaving" : {
      "type" : "boolean",
      "description" : "Avoids consuming fuel when heat is 100%"
    },
    "engineHeatChangeExponent" : {
      "type" : "number",
      "format" : "float",
      "description" : "Increases heat gained at low heat level, and increased heat decreases when at high heat and not consuming fuel"
    },
    "engineHeatGain" : {
      "type" : "number",
      "format" : "float",
      "description" : "The amount of heat a gain per tick (when burning)"
    },
    "engineHeatLoss" : {
      "type" : "number",
      "format" : "float",
      "description" : "The amount of heat a engine loses per tick"
    },
    "engineMinCapacity" : {
      "type" : "integer",
      "format" : "int32",
      "description" : "Increasing this value will result in more items being able to converted to fuel"
    },
    "enginePowerAngular" : {
      "type" : "number",
      "format" : "float",
      "description" : "Turning power per engine when heated fully"
    },
    "enginePowerAngularMin" : {
      "type" : "number",
      "format" : "float",
      "description" : "Turning power per engine when minimal heat"
    },
    "enginePowerLinear" : {
      "type" : "number",
      "format" : "float",
      "description" : "Movement power per engine when heated fully"
    },
    "enginePowerLinearMin" : {
      "type" : "number",
      "format" : "float",
      "description" : "Movement power per engine with minimal heat"
    },
    "engineRedstoneBehaviorPause" : {
      "type" : "boolean",
      "description" : "Pause fuel consumption and power when block is powered"
    },
    "floaterBuoyantFactorPerKg" : {
      "type" : "number",
      "format" : "double",
      "description" : "The amount extra that each floater will make the ship float, per kg mass"
    },
    "linearStabilizeMaxAntiVelocity" : {
      "type" : "number",
      "format" : "double",
      "description" : "How fast a ship will stop. 1 = fast stop, 0 = slow stop"
    },
    "massPerBalloon" : {
      "type" : "number",
      "format" : "double",
      "description" : "Amount of mass in kg a balloon can lift"
    },
    "maxCasualSpeed" : {
      "type" : "number",
      "format" : "double",
      "description" : "Max speed of a ship without boosting"
    },
    "maxFloaterBuoyantFactor" : {
      "type" : "number",
      "format" : "double",
      "description" : "The maximum amount extra each floater will multiply the buoyant force by, irrespective of mass"
    },
    "maxShipBlocks" : {
      "type" : "integer",
      "format" : "int32",
      "description" : "Maximum number of blocks allowed in a ship. Set to 0 for no limit"
    },
    "maxSizeForTurnSpeedPenalty" : {
      "type" : "number",
      "format" : "double",
      "description" : "The maximum distance from center of mass to one end of the ship considered by the turn speed. At it's default of 16, it ensures that really large ships will turn at the same speed as a ship with a center of mass only 16 blocks away from the farthest point in the ship. That way, large ships do not turn painfully slowly"
    },
    "popSideBalloonChance" : {
      "type" : "number",
      "format" : "double",
      "description" : "Chance for popped balloons to pop adjacent balloons, per side"
    },
    "stabilizationSpeed" : {
      "type" : "number",
      "format" : "double",
      "description" : "The speed at which the ship stabilizes"
    },
    "stabilizationTorqueConstant" : {
      "type" : "number",
      "format" : "double",
      "description" : "How much torque a ship will apply to try and keep level"
    },
    "turnAcceleration" : {
      "type" : "number",
      "format" : "double",
      "description" : "The maximum linear acceleration at any point on the ship caused by helm torque"
    },
    "turnSpeed" : {
      "type" : "number",
      "format" : "double",
      "description" : "The maximum linear velocity at any point on the ship caused by helm torque"
    },
    "$schema" : {
      "type" : "string"
    }
  },
  "additionalProperties" : false
}

=== Rodrigo816/Create-chronicles-bosses-and-beyond/config/valkyrienskies/vs_eureka_server.json
{
  "enginePowerLinear" : 2000000.0,
  "enginePowerLinearMin" : 10000.0,
  "enginePowerAngular" : 1.0,
  "enginePowerAngularMin" : 0.0,
  "engineHeatLoss" : 0.01,
  "engineHeatGain" : 0.03,
  "engineHeatChangeExponent" : 0.1,
  "engineRedstoneBehaviorPause" : false,
  "engineFuelSaving" : false,
  "engineMinCapacity" : 2000,
  "engineFuelMultiplier" : 2.0,
  "maxCasualSpeed" : 15.0,
  "stabilizationSpeed" : 10.0,
  "floaterBuoyantFactorPerKg" : 50000.0,
  "maxFloaterBuoyantFactor" : 1.0,
  "baseSpeed" : 3.0,
  "baseImpulseElevationRate" : 2.0,
  "balloonElevationMaxSpeed" : 5.5,
  "elevationSnappiness" : 1.0,
  "doFluidDrag" : false,
  "massPerBalloon" : 5000.0,
  "turnSpeed" : 3.0,
  "turnAcceleration" : 10.0,
  "maxSizeForTurnSpeedPenalty" : 16.0,
  "stabilizationTorqueConstant" : 15.0,
  "linearStabilizeMaxAntiVelocity" : 1.0,
  "antiVelocityMassRelevance" : 0.8,
  "popSideBalloonChance" : 0.3,
  "blockBlacklist" : [ "vs_eureka:ship_helm", "minecraft:dirt", "minecraft:grass_block", "minecraft:grass_path", "minecraft:stone", "minecraft:bedrock", "minecraft:sand", "minecraft:gravel", "minecraft:water", "minecraft:flowing_water", "minecraft:lava", "minecraft:flowing_lava", "minecraft:lily_pad", "minecraft:coarse_dirt", "minecraft:podzol", "minecraft:granite", "minecraft:diorite", "minecraft:andesite", "minecraft:deepslate", "minecraft:tuff", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:red_sand", "minecraft:sandstone", "minecraft:end_stone", "minecraft:red_sandstone", "minecraft:blackstone", "minecraft:netherrack", "minecraft:soul_sand", "minecraft:soul_soil", "minecraft:grass", "minecraft:fern", "minecraft:dead_bush", "minecraft:seagrass", "minecraft:tall_seagrass", "minecraft:sea_pickle", "minecraft:kelp", "minecraft:bamboo", "minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium", "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy", "minecraft:cornflower", "minecraft:lily_of_the_valley", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:crimson_fungus", "minecraft:warped_fungus", "minecraft:crimson_roots", "minecraft:warped_roots", "minecraft:nether_sprouts", "minecraft:weeping_vines", "minecraft:twisting_vines", "minecraft:chorus_plant", "minecraft:chorus_flower", "minecraft:snow", "minecraft:snow_block", "minecraft:cactus", "minecraft:vine", "minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:tall_grass", "minecraft:large_fern", "minecraft:air", "minecraft:ice", "minecraft:packed_ice", "minecraft:blue_ice", "minecraft:portal", "minecraft:end_portal_frame", "minecraft:end_portal", "minecraft:end_gateway", "minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:birch_leaves", "minecraft:jungle_leaves", "minecraft:acacia_leaves", "minecraft:dark_oak_leaves" ],
  "diagonals" : true,
  "ballastWeight" : 10000.0,
  "ballastNoWeight" : 1000.0,
  "allowDisassembly" : true,
  "maxShipBlocks" : 32768,
  "$schema" : "schemas/vs_eureka_server.schema.json"
}
